config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  get 'users/new'

  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/github', as: 'github_login'
  get 'auth/facebook', as: 'facebook_login'
  get '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true

  def self.create_from_github(auth)
    User.create!(
      github_id: auth['uid'],
      # nickname: auth['info']['nickname'],
      email: auth['info']['email']
    )
  end

  def self.create_from_facebook(auth)
    User.create!(
      facebook_id: auth['uid'],
      name: auth['info']['name'],
      email: auth['info']['email'],
      user_likes: auth['info']['user_likes']
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #login
  def create
    # omniauth middleware stores oauth data in the
    # request.env (not in params)
    auth = request.env["omniauth.auth"]


    # if user exists, log her in
    # else, create the user, and log her in
    if auth['provider'] == "github"
      user = User.find_by(github_id: auth['uid']) ||
        User.create_from_github(auth)
    elsif auth['provider'] == "facebook"
      user = User.find_by(facebook_id: auth['uid']) ||
        User.create_from_facebook(auth)
    end

    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed In!"
  end

  # logout
  def destroy
    reset_session
    redirect_to root_url, notice: 'Signed out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OmniauthExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<em><%= notice %></em>
<% if current_user %>
  Welcome <%= current_user.name %>!
  <%= link_to "Sign Out", logout_path %>
  <%= current_user.user_likes %>
<% else %>
  Please sign in!<br>
  <%= link_to "Sign in with Github", github_login_path %>
  <%= link_to "Sign in with Facebook", facebook_login_path %>
<% end %>